apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simple-service
  name: simple-service
spec:
  ports:
  - port: 3030
    protocol: TCP
    targetPort: 3030
  selector:
    app: simple-service
status:
  loadBalancer: {}
