apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service-discovery
  name: service-discovery-main
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: service-discovery
status:
  loadBalancer: {}
